# ==== ruff ====
[tool.ruff]
line-length = 88 # black default is 88

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F"]
ignore = []
fixable = ["ALL"]
unfixable = []

[tool.ruff.lint.per-file-ignores]
"*/__init__.py" = ["F401", "F403"]

[tool.ruff.format]
quote-style = "double"              # black default is double
indent-style = "space"              # black default is space
skip-magic-trailing-comma = false   # black default is false
line-ending = "auto"                # black default is auto
exclude = ["**/migrations/**/*.py"]

# ==== djlint ====
[tool.djlint]
profile = "django"
# H006: Ignore because img sizes are often set with tailwind
ignore = "H006"
max_attribute_length = 0              # always wrap attributes
format_attribute_template_tags = true
format_js = true
format_css = true

[tool.djlint.js]
templating = "django"

# ==== mypy ====
[tool.mypy]
# Disallow dynamic typing
# disallow_any_unimported = True
# disallow_any_expr = True
# disallow_any_decorated = True
# disallow_any_explicit = True
# disallow_subclassing_any = True  # --> These are very harsh. We can check them later again if needed.
disallow_any_generics = true

# Disallow untyped definitions and calls
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
# disallow_untyped_decorators = True

# None and optional handling
no_implicit_optional = true

# Configuring warnings
warn_unused_ignores = true
warn_no_return = true
warn_return_any = false
warn_redundant_casts = true

# Misc things
strict_equality = true

# Config file
warn_unused_configs = true

# Ignore
follow_imports = "skip"
ignore_missing_imports = true
exclude = "migrations|settings.py|manage.py|venv|__init__.py"
